<?php

use Drupal\Core\Render\Element;

/**
 * Implements hook_field_info_alter().
 */
function cn_display_field_info_alter(&$info) {
  if (!empty($info['FontFieldIcon'])) {
    $info['FontFieldIcon']['class'] = \Drupal\cn_display\Plugin\Field\FieldType\FontFieldIcon::class;
  }
}

/**
 * Implements hook_field_widget_info_alter().
 */
function cn_display_field_widget_info_alter(array &$info) {
  if (!empty($info['FontFieldIconDefaultWidget'])) {
    $info['FontFieldIconDefaultWidget']['class'] = \Drupal\cn_display\Plugin\Field\FieldWidget\FontFieldIconDefaultWidget::class;
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function cn_display_field_formatter_info_alter(array &$info) {
  if (!empty($info['FontFieldIconDefaultFormatter'])) {
    $info['FontFieldIconDefaultFormatter']['class'] = \Drupal\cn_display\Plugin\Field\FieldFormatter\FontFieldIconDefaultFormatter::class;
  }
}

/**
 * Implements hook_ENTITY_TYPE_load().
 */
function cn_display_node_load(array $entities) {
  \Drupal::service('entity.default_field_value')->setDefaults($entities);
}
